// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "ping the server to check if it running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "ping the server",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/twin/{twin_id}": {
            "post": {
                "description": "submit the message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RMB"
                ],
                "summary": "submit the message",
                "parameters": [
                    {
                        "description": "rmb.Message",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rmbproxy.Message"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "twin id",
                        "name": "twin_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rmbproxy.MessageIdentifier"
                        }
                    }
                }
            }
        },
        "/twin/{twin_id}/{retqueue}": {
            "get": {
                "description": "Get the message result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RMB"
                ],
                "summary": "Get the message result",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "twin id",
                        "name": "twin_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "message retqueue",
                        "name": "retqueue",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/rmbproxy.Message"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rmbproxy.Message": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string",
                    "example": "zos.statistics.get"
                },
                "dat": {
                    "type": "string"
                },
                "dst": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "example": 2
                    }
                },
                "err": {
                    "type": "string"
                },
                "exp": {
                    "type": "integer",
                    "example": 0
                },
                "now": {
                    "type": "integer",
                    "example": 1631078674
                },
                "ret": {
                    "type": "string"
                },
                "shm": {
                    "type": "string"
                },
                "src": {
                    "type": "integer",
                    "example": 1
                },
                "try": {
                    "type": "integer",
                    "example": 2
                },
                "uid": {
                    "type": "string"
                },
                "ver": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "rmbproxy.MessageIdentifier": {
            "type": "object",
            "properties": {
                "retqueue": {
                    "type": "string",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
